name: Build and Test

on:
  pull_request:
    branches:
      - dev
      - main
      - release/*

jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.4'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build versioneer black pytest

      - name: Format code with Black
        run: black --check .

      - name: Run tests
        run: pytest

      - name: Build Python package
        run: python -m build

      - name: Upload Python package
        uses: actions/upload-artifact@v4
        with:
          name: python-package
          path: dist/*
          retention-days: 1
